import './globals.css'
import Navigaiton from '@/components/Navigaiton'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My 2nd Nextjs App',
  description: 'Generated by create next app',
  keywords: 'nextjs, react, app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/5/flatly/bootstrap.min.css"
        />
      </head>
      <body className={inter.className}>
        <Navigaiton />
        <div className="container p-4"> {children}</div>
      </body>
    </html>
  )
}
